version: 1
disable_existing_loggers: False

formatters:
    console:
        format: "%(message)s"
    standard:
        format: '%(asctime)s - %(name)2s:%(lineno)s - %(funcName)3s: %(levelname)3s %(message)s'
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: console
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /var/log/tank_control/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /var/log/tank_control/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /var/log/tank_control/debug.log
        maxBytes: 10485760
        backupCount: 2
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /var/log/tank_control/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: standard
        filename: /var/log/tank_control/warning.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    notification_file_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: /var/log/tank_control/notifications.log
      maxBytes: 10485760 # 10MB
      backupCount: 2
      encoding: utf8

    use_database_file_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: /var/log/tank_control/use_database.log
      maxBytes: 10485760 # 10MB
      backupCount: 2
      encoding: utf8

    tank_control_master_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: /var/log/tank_control/tank_control_master.log
      maxBytes: 10485760 # 10MB
      backupCount: 2
      encoding: utf8

    power_strip_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: /var/log/tank_control/power_strip.log
      maxBytes: 10485760 # 10MB
      backupCount: 2
      encoding: utf8

    flask_route_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: standard
      filename: /var/log/tank_control/routes.log
      maxBytes: 100000
      backupCount: 3
      encoding: utf8

root:
    level: NOTSET
    handlers:
    propogate: no

loggers:
    __main__:
        handlers: [console, flask_route_handler, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warning_file_handler, tank_control_master_handler]
        propogate: no

    notifications:
        handlers: [console, flask_route_handler, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warning_file_handler, notification_file_handler]
        propogate: yes

    use_database:
        handlers: [console, flask_route_handler, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warning_file_handler, use_database_file_handler]
        propogate: yes

    power_strip:
      handlers: [console, flask_route_handler, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warning_file_handler, power_strip_handler]
      propogate: yes

    routes:
      handlers: [console, flask_route_handler, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warning_file_handler, flask_route_handler]
      propogate: yes

